@startuml OmronController
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml

title Omron C4 State diagram

state "Plate holes seen?" as holescheck
state "Difference <= 4?" as differencecheck

state "Camera Image Input" as camerainput : do / Take photo
state "Shape Search III" as shapesearchIII : do / Determine position
state "Get error" as resulterror : do / Result output
state "Plate aligned" as resultoutput : do / Result output
state "Send difference" as dataoutput : do / Calculate difference
dataoutput : do / Data output

[*] --> camerainput
camerainput --> shapesearchIII
shapesearchIII --> holescheck
holescheck --> differencecheck : Yes
holescheck --> resulterror : No
differencecheck --> dataoutput : No
differencecheck --> resultoutput : Yes
dataoutput --> [*]
resultoutput --> [*]
resulterror --> [*]

@enduml